/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import static java.awt.SystemColor.desktop;
import javaapplication1.bPkg.BusBoyFrame;
import javaapplication1.cPkg.CookFrame;
import javaapplication1.hPkg.HostFrame;
import javaapplication1.mPkg.ManagerFrame;
import javaapplication1.wPkg.WaiterFrame;

/**
 *
 * @author Gerald
 */
public class RMS1 extends javax.swing.JFrame {

    /**
     * Creates new form RMS1
     */
    public RMS1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        loginT = new javax.swing.JMenuBar();
        nullExit = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        login = new javax.swing.JMenu();
        manager = new javax.swing.JMenuItem();
        waiter = new javax.swing.JMenuItem();
        cook = new javax.swing.JMenuItem();
        host = new javax.swing.JMenuItem();
        busBoy = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        loginT.setBackground(new java.awt.Color(255, 255, 0));
        loginT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        nullExit.setText("Exit");
        nullExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nullExitActionPerformed(evt);
            }
        });

        exit.setText("Close");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        nullExit.add(exit);

        loginT.add(nullExit);

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        manager.setText("Manager");
        manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerActionPerformed(evt);
            }
        });
        login.add(manager);

        waiter.setText("Waiter");
        waiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waiterActionPerformed(evt);
            }
        });
        login.add(waiter);

        cook.setText("Cook");
        cook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookActionPerformed(evt);
            }
        });
        login.add(cook);

        host.setText("Host");
        host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostActionPerformed(evt);
            }
        });
        login.add(host);

        busBoy.setText("BusBoy");
        busBoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busBoyActionPerformed(evt);
            }
        });
        login.add(busBoy);

        loginT.add(login);

        setJMenuBar(loginT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nullExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nullExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_nullExitActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        ManagerFrame a = new ManagerFrame();
        desktop.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerActionPerformed
        // TODO add your handling code here:
        new ManagerFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managerActionPerformed

    private void waiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterActionPerformed
        // TODO add your handling code here:
        new WaiterFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_waiterActionPerformed

    private void cookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookActionPerformed
        // TODO add your handling code here:
        new CookFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cookActionPerformed

    private void hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostActionPerformed
        // TODO add your handling code here:
        new HostFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hostActionPerformed

    private void busBoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busBoyActionPerformed
        // TODO add your handling code here:
        new BusBoyFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_busBoyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RMS1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem busBoy;
    private javax.swing.JMenuItem cook;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem host;
    private javax.swing.JMenu login;
    private javax.swing.JMenuBar loginT;
    private javax.swing.JMenuItem manager;
    private javax.swing.JMenu nullExit;
    private javax.swing.JMenuItem waiter;
    // End of variables declaration//GEN-END:variables
}
