/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1.acctFrames;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javaapplication1.acctFrames.dPanels.ePanel;
import javaapplication1.acctFrames.dPanels.mPanel;

/**
 *
 * @author Gerald
 */
public class acctFrame extends javax.swing.JInternalFrame {
    GridBagLayout layout = new GridBagLayout();
    ePanel ep;
    mPanel mp;

    /**
     * Creates new form acctFrame
     */
    public acctFrame() {
        initComponents();
        ep = new ePanel();
        mp = new mPanel();
        dynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        dynamicPanel.add(ep, c);
        c.gridx = 0;
        c.gridy = 0;
        dynamicPanel.add(mp, c);
        ep.setVisible(true);
        mp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActions = new javax.swing.JPanel();
        createO = new javax.swing.JButton();
        changeO = new javax.swing.JButton();
        finishP = new javax.swing.JButton();
        tableS = new javax.swing.JButton();
        dynamicPanel = new javax.swing.JPanel();

        panelActions.setBackground(new java.awt.Color(255, 204, 204));

        createO.setText("Create Order");
        createO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOActionPerformed(evt);
            }
        });

        changeO.setText("Change Order");
        changeO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeOActionPerformed(evt);
            }
        });

        finishP.setText("Finish & Pay");

        tableS.setText("Change Table Status");

        javax.swing.GroupLayout panelActionsLayout = new javax.swing.GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tableS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finishP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(createO)
                .addGap(18, 18, 18)
                .addComponent(changeO)
                .addGap(18, 18, 18)
                .addComponent(finishP)
                .addGap(18, 18, 18)
                .addComponent(tableS)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(panelActions, java.awt.BorderLayout.LINE_START);

        dynamicPanel.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout dynamicPanelLayout = new javax.swing.GroupLayout(dynamicPanel);
        dynamicPanel.setLayout(dynamicPanelLayout);
        dynamicPanelLayout.setHorizontalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        dynamicPanelLayout.setVerticalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        getContentPane().add(dynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeOActionPerformed
        // TODO add your handling code here:
        ep.setVisible(false);
        mp.setVisible(true);
    }//GEN-LAST:event_changeOActionPerformed

    private void createOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOActionPerformed
        // TODO add your handling code here:
        ep.setVisible(true);
        mp.setVisible(false);
    }//GEN-LAST:event_createOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeO;
    private javax.swing.JButton createO;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JButton finishP;
    private javax.swing.JPanel panelActions;
    private javax.swing.JButton tableS;
    // End of variables declaration//GEN-END:variables
}
