/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1.cPkg;


import java.awt.event.*;
import javaapplication1.RMS1;
import javaapplication1.wPkg.WaiterFrame;

import javaapplication1.RMS.*;
import javax.swing.*;
import javax.swing.GroupLayout;

/**
 *
 * @author DustedPixels
 */
public class CookFrame extends javax.swing.JFrame {

    private static OrderManager orderManager;
    /**
     * Creates new form CookFrame
     */
	private void completedTopOrderActionPerformed(ActionEvent e) {
		orderManager.removeFromOrderQueue();
		textArea1.setText(orderManager.printAllOrders());
	}

	private void completeOrderActionPerformed(ActionEvent e) {
        Order order = orderManager.peek();
        Notification notification = new Notification(order);
        orderManager.completeOrder();

        HandheldDevice handheldDevice = new HandheldDevice();


        new WaiterFrame(handheldDevice, notification).setVisible(true);
        this.dispose();

	}

    public CookFrame(OrderManager orderManager) {
	    this.orderManager = orderManager;
        initComponents(orderManager);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	// Generated using JFormDesigner Evaluation license - unknown
	private void initComponents(OrderManager orderManager) {
		back = new JButton();
		scrollPane1 = new JScrollPane();
		textArea1 = new JTextArea(orderManager.printAllOrders());
		button1 = new JButton();
		button2 = new JButton();

		//======== this ========
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		var contentPane = getContentPane();

		//---- back ----
		back.setText("Back");
		back.addActionListener(e -> backActionPerformed(e));

		//======== scrollPane1 ========
		{
			scrollPane1.setViewportView(textArea1);
		}

		//---- button1 ----
		button1.setText("Complete Order");
		button1.addActionListener(e -> completeOrderActionPerformed(e));

		//---- button2 ----
		button2.setText("Completed Top Order");
		button2.addActionListener(e -> completedTopOrderActionPerformed(e));

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(contentPaneLayout.createParallelGroup()
						.addGroup(contentPaneLayout.createSequentialGroup()
							.addComponent(back)
							.addContainerGap(314, Short.MAX_VALUE))
						.addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
							.addGap(0, 76, Short.MAX_VALUE)
							.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
								.addComponent(scrollPane1)
								.addGroup(contentPaneLayout.createSequentialGroup()
									.addComponent(button2)
									.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(button1)))
							.addGap(41, 41, 41))))
		);
		contentPaneLayout.setVerticalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(back)
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(scrollPane1, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
					.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
						.addComponent(button1)
						.addComponent(button2))
					.addContainerGap(11, Short.MAX_VALUE))
		);
		pack();
		setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new RMS1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OrderManager orderManager = new OrderManager();
                new CookFrame(orderManager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
	// Generated using JFormDesigner Evaluation license - unknown
	private JButton back;
	private JScrollPane scrollPane1;
	private JTextArea textArea1;
	private JButton button1;
	private JButton button2;
    // End of variables declaration//GEN-END:variables
}
