/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1.wPkg;

/**
 *
 * @author DustedPixels
 */
public class SelectStuffFrame extends javax.swing.JFrame {

    /**
     * Creates new form SelectFrame
     */
    public SelectStuffFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        table01 = new javax.swing.JLabel();
        table02 = new javax.swing.JLabel();
        table03 = new javax.swing.JLabel();
        table04 = new javax.swing.JLabel();
        table05 = new javax.swing.JLabel();
        table06 = new javax.swing.JLabel();
        table07 = new javax.swing.JLabel();
        table08 = new javax.swing.JLabel();
        table09 = new javax.swing.JLabel();
        table10 = new javax.swing.JLabel();
        table11 = new javax.swing.JLabel();
        table12 = new javax.swing.JLabel();
        table13 = new javax.swing.JLabel();
        table14 = new javax.swing.JLabel();
        table15 = new javax.swing.JLabel();
        table16 = new javax.swing.JLabel();
        table17 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Select table");

        table01.setText("Table 1");
        table01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table01MouseClicked(evt);
            }
        });

        table02.setText("Table 2");

        table03.setText("Table 3");

        table04.setText("Table 4");

        table05.setText("Table 5");

        table06.setText("Table 6");

        table07.setText("Table 7");

        table08.setText("Table 8");

        table09.setText("Table 9");

        table10.setText("Table 10");

        table11.setText("Table 11");

        table12.setText("Table 12");

        table13.setText("Table 13");

        table14.setText("Table 14");

        table15.setText("Table 15");

        table16.setText("Table 16");

        table17.setText("Table 17");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table09)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(table08)
                            .addComponent(table07)
                            .addComponent(table01)
                            .addComponent(table02)
                            .addComponent(table03)
                            .addComponent(table04)
                            .addComponent(table05)
                            .addComponent(table06))
                        .addGap(72, 72, 72)
                        .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(table11)
                            .addComponent(table17)
                            .addComponent(table16)
                            .addComponent(table15)
                            .addComponent(table14)
                            .addComponent(table13)
                            .addComponent(table12)
                            .addComponent(table10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addComponent(table13)
                        .addGap(18, 18, 18)
                        .addComponent(table14)
                        .addGap(18, 18, 18)
                        .addComponent(table15)
                        .addGap(18, 18, 18)
                        .addComponent(table16)
                        .addGap(18, 18, 18)
                        .addComponent(table17))
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(table01)
                            .addComponent(table10))
                        .addGap(14, 14, 14)
                        .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(table02)
                            .addComponent(table11))
                        .addGap(18, 18, 18)
                        .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(table03)
                            .addComponent(table12))
                        .addGap(22, 22, 22)
                        .addComponent(table04)
                        .addGap(18, 18, 18)
                        .addComponent(table05)
                        .addGap(18, 18, 18)
                        .addComponent(table06)
                        .addGap(18, 18, 18)
                        .addComponent(table07)
                        .addGap(18, 18, 18)
                        .addComponent(table08)))
                .addGap(18, 18, 18)
                .addComponent(table09)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new WaiterFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void table01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table01MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_table01MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectStuffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectStuffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectStuffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectStuffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectStuffFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel table01;
    private javax.swing.JLabel table02;
    private javax.swing.JLabel table03;
    private javax.swing.JLabel table04;
    private javax.swing.JLabel table05;
    private javax.swing.JLabel table06;
    private javax.swing.JLabel table07;
    private javax.swing.JLabel table08;
    private javax.swing.JLabel table09;
    private javax.swing.JLabel table10;
    private javax.swing.JLabel table11;
    private javax.swing.JLabel table12;
    private javax.swing.JLabel table13;
    private javax.swing.JLabel table14;
    private javax.swing.JLabel table15;
    private javax.swing.JLabel table16;
    private javax.swing.JLabel table17;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
