/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.border.*;
import static java.awt.SystemColor.desktop;

import javaapplication1.RMS.HandheldDevice;
import javaapplication1.RMS.OrderManager;
import javaapplication1.bPkg.BusBoyFrame;
import javaapplication1.cPkg.CookFrame;
import javaapplication1.hPkg.HostFrame;
import javaapplication1.mPkg.ManagerFrame;
import javaapplication1.wPkg.WaiterFrame;

/**
 *
 * @author Gerald
 */
public class RMS1 extends javax.swing.JFrame {

	private HandheldDevice handheldDevice = new HandheldDevice();
	private OrderManager orderManager = new OrderManager();
    /**
     * Creates new form RMS1
     */
    public RMS1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	// Generated using JFormDesigner Evaluation license - unknown
	private void initComponents() {
		loginT = new JMenuBar();
		nullExit = new JMenu();
		exit = new JMenuItem();
		login = new JMenu();
		manager = new JMenuItem();
		waiter = new JMenuItem();
		cook = new JMenuItem();
		host = new JMenuItem();
		busBoy = new JMenuItem();
		desktop = new JDesktopPane();

		//======== this ========
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		var contentPane = getContentPane();

		//======== loginT ========
		{
			loginT.setBackground(Color.yellow);
			loginT.setBorder(new EmptyBorder(1, 1, 1, 1));

			//======== nullExit ========
			{
				nullExit.setText("Exit");
				nullExit.addActionListener(e -> nullExitActionPerformed(e));

				//---- exit ----
				exit.setText("Close");
				exit.addActionListener(e -> exitActionPerformed(e));
				nullExit.add(exit);
			}
			loginT.add(nullExit);

			//======== login ========
			{
				login.setText("Login");
				login.addActionListener(e -> loginActionPerformed(e));

				//---- manager ----
				manager.setText("Manager");
				manager.addActionListener(e -> managerActionPerformed(e));
				login.add(manager);

				//---- waiter ----
				waiter.setText("Waiter");
				waiter.addActionListener(e -> waiterActionPerformed(e));
				login.add(waiter);

				//---- cook ----
				cook.setText("Cook");
				cook.addActionListener(e -> cookActionPerformed(e));
				login.add(cook);

				//---- host ----
				host.setText("Host");
				host.addActionListener(e -> hostActionPerformed(e));
				login.add(host);

				//---- busBoy ----
				busBoy.setText("BusBoy");
				busBoy.addActionListener(e -> busBoyActionPerformed(e));
				login.add(busBoy);
			}
			loginT.add(login);
		}
		setJMenuBar(loginT);

		//======== desktop ========
		{
			desktop.setBackground(new Color(51, 51, 51));

			GroupLayout desktopLayout = new GroupLayout(desktop);
			desktop.setLayout(desktopLayout);
			desktopLayout.setHorizontalGroup(
				desktopLayout.createParallelGroup()
					.addGap(0, 526, Short.MAX_VALUE)
			);
			desktopLayout.setVerticalGroup(
				desktopLayout.createParallelGroup()
					.addGap(0, 315, Short.MAX_VALUE)
			);
		}

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(
			contentPaneLayout.createParallelGroup()
				.addComponent(desktop)
		);
		contentPaneLayout.setVerticalGroup(
			contentPaneLayout.createParallelGroup()
				.addComponent(desktop)
		);
		pack();
		setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void nullExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nullExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_nullExitActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        ManagerFrame a = new ManagerFrame();
        desktop.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerActionPerformed
        // TODO add your handling code here:
        new ManagerFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managerActionPerformed

    private void waiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterActionPerformed
        // TODO add your handling code here:
        new WaiterFrame(handheldDevice).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_waiterActionPerformed

    private void cookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookActionPerformed
        // TODO add your handling code here:
        new CookFrame(orderManager).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cookActionPerformed

    private void hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostActionPerformed
        // TODO add your handling code here:
        new HostFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hostActionPerformed

    private void busBoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busBoyActionPerformed
        // TODO add your handling code here:
        new BusBoyFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_busBoyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RMS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RMS1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
	// Generated using JFormDesigner Evaluation license - unknown
	private JMenuBar loginT;
	private JMenu nullExit;
	private JMenuItem exit;
	private JMenu login;
	private JMenuItem manager;
	private JMenuItem waiter;
	private JMenuItem cook;
	private JMenuItem host;
	private JMenuItem busBoy;
	private JDesktopPane desktop;
    // End of variables declaration//GEN-END:variables
}
