/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1.wPkg;

import java.awt.event.*;
import javaapplication1.RMS.HandheldDevice;
import javaapplication1.RMS.Notification;
import javaapplication1.RMS1;
import javaapplication1.RMS1;
import javax.swing.*;
import javax.swing.GroupLayout;

/**
 *
 * @author DustedPixels
 */
public class WaiterFrame extends javax.swing.JFrame {

    private HandheldDevice handheldDevice;
    private Notification notification;
    /**
     * Creates new form WaiterFrame
     */
    public WaiterFrame(HandheldDevice handheldDevice) {
        this.handheldDevice = handheldDevice;
        initComponents();
    }

	private void button1ActionPerformed(ActionEvent e) {
		textArea1.setText("");
	}

    public WaiterFrame(HandheldDevice handheldDevice, Notification notification){
		this.handheldDevice = handheldDevice;
		this.notification = notification;
		initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	// Generated using JFormDesigner Evaluation license - unknown
	private void initComponents() {
		handleOrder = new JToggleButton();
		back = new JButton();
		scrollPane1 = new JScrollPane();
	    if (this.notification == null){
		    textArea1 = new JTextArea();
	    }
	    else {
		    textArea1 = new JTextArea(this.notification.getNotification());
	    }
		label1 = new JLabel();
		button1 = new JButton();

		//======== this ========
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		var contentPane = getContentPane();

		//---- handleOrder ----
		handleOrder.setText("Handle Order");
		handleOrder.addActionListener(e -> handleOrderActionPerformed(e));

		//---- back ----
		back.setText("Back");
		back.addActionListener(e -> backActionPerformed(e));

		//======== scrollPane1 ========
		{
			scrollPane1.setViewportView(textArea1);
		}

		//---- label1 ----
		label1.setText("Active Notifications");
		label1.setLabelFor(textArea1);

		//---- button1 ----
		button1.setText("Order Delivered");
		button1.addActionListener(e -> {
			button1ActionPerformed(e);
			button1ActionPerformed(e);
		});

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
						.addGroup(contentPaneLayout.createSequentialGroup()
							.addComponent(back)
							.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
							.addGroup(contentPaneLayout.createParallelGroup()
								.addComponent(label1)
								.addGroup(contentPaneLayout.createSequentialGroup()
									.addGap(175, 175, 175)
									.addComponent(handleOrder))))
						.addGroup(contentPaneLayout.createSequentialGroup()
							.addGap(0, 92, Short.MAX_VALUE)
							.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
								.addComponent(button1)
								.addComponent(scrollPane1, GroupLayout.PREFERRED_SIZE, 280, GroupLayout.PREFERRED_SIZE))))
					.addGap(20, 20, 20))
		);
		contentPaneLayout.setVerticalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
						.addComponent(back)
						.addComponent(handleOrder))
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(label1)
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(scrollPane1, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
					.addGap(18, 18, 18)
					.addComponent(button1)
					.addGap(9, 9, 9))
		);
		pack();
		setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new RMS1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void handleOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleOrderActionPerformed
        // TODO add your handling code here:
        new SelectStuffFrame(this.handheldDevice).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_handleOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaiterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaiterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaiterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaiterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaiterFrame(handheldDevice).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
	// Generated using JFormDesigner Evaluation license - unknown
	private JToggleButton handleOrder;
	private JButton back;
	private JScrollPane scrollPane1;
	private JTextArea textArea1;
	private JLabel label1;
	private JButton button1;
    // End of variables declaration//GEN-END:variables
}
